version: '3'
x-airflow-common:
  &airflow-common
  build: .
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
    AIRFLOW__CORE__LOGGING_LEVEL: INFO

  volumes:
    - ./dags:/home/airflow/dags
    - ./logs:/home/airflow/logs
    - ./plugins:/home/airflow/plugins
    - ./temp:/home/airflow/temp
    - ./airflow-config/airflow.cfg:/opt/airflow/airflow.cfg
    
services:
  postgres:
    image: postgres:13
    container_name: raizen_airflow_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=airflow
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"

  airflow-init:
    << : *airflow-common
    container_name: raizen_airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - (airflow users list | grep airflow) || ( airflow db init &&
        airflow users create
          --role Admin
          --username airflow
          --password airflow
          --email airflow@airflow.com
          --firstname airflow
          --lastname airflow )
    restart: on-failure

  airflow-webserver:
    << : *airflow-common
    command: airflow webserver
    ports:
      - 8080:8080
    container_name: raizen_airflow_webserver
    restart: always

  airflow-scheduler:
    << : *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - sleep 30 && airflow scheduler
    container_name: raizen_airflow_scheduler
    restart: always